# Generated by Django 3.1.7 on 2021-03-20 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0004_auto_20210320_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='department',
            field=models.ForeignKey(blank=True, default='2', null=True, on_delete=django.db.models.deletion.CASCADE, to='budget.department'),
        ),
    ]
