# Generated by Django 3.1.7 on 2021-03-20 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0005_auto_20210320_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='budget_monthly',
            field=models.IntegerField(default=50000),
        ),
    ]
