# Generated by Django 3.1.7 on 2021-04-07 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0007_auto_20210320_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='budget_monthly',
            field=models.IntegerField(default=50000),
        ),
        migrations.DeleteModel(
            name='Budget',
        ),
    ]
