# Generated by Django 3.1.7 on 2021-04-08 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0010_auto_20210408_1357'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expenses',
            old_name='form_status',
            new_name='form_status_head',
        ),
        migrations.AddField(
            model_name='expenses',
            name='form_status_payment',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
