# Generated by Django 3.1.7 on 2021-04-10 04:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0011_auto_20210408_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='travel_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
